{% set name = "pygit2" %}
{% set version = "1.0.2" %}
{% set sha256 = "b7c0abce8cfe4b570e78d16627fe44e76004a96f6cb1c77c8a3ffe8ce37dd2b0" %}

# must pin the appropiate libgit2 version documented here:
# https://www.pygit2.org/install.html#version-numbers

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  features:
    - vc10   # [win and py34]
    - vc14   # [win and py35]
  skip: True  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - python
    - pip
    - cffi
    - libgit2 0.28.*

  run:
    - python
    - cffi
    - six
    - libgit2 0.28.*

test:
  imports:
    - pygit2

about:
  home: http://github.com/libgit2/pygit2
  summary: 'Python bindings for libgit2.'
  license: GPLv2 with linking exception
  license_family: GPL2
  license_file: COPYING
  doc_url: http://www.pygit2.org/
  dev_url: https://github.com/libgit2/pygit2

extra:
  recipe-maintainers:
    - kszucs
