{% set name = "pygit2" %}
{% set version = "1.10.1" %}

# must pin the appropiate libgit2 version documented here:
# https://www.pygit2.org/install.html#version-numbers

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 354651bf062c02d1f08041d6fbf1a9b4bf7a93afce65979bdc08bdc65653aa2e

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}

  host:
    - python
    - pip
    - cffi
    - libgit2 1.5

  run:
    - python
    - cached-property
    - cffi
    - six

test:
  imports:
    - pygit2

about:
  home: http://github.com/libgit2/pygit2
  summary: Python bindings for libgit2.
  license: GPL-2.0-only WITH GCC-exception-2.0
  license_family: GPL
  license_file: COPYING
  doc_url: http://www.pygit2.org/
  dev_url: https://github.com/libgit2/pygit2

extra:
  recipe-maintainers:
    - efiop
    - kszucs
    - xhochy
