travis:
  secure:
    BINSTAR_TOKEN: lDFGNoAasoL3Ynj4ViOpvfKDU8/6+1cMXCznApN6NMTfad/Z0ZHYrmgn0UazSf0vevTm4UMiFmyl/nQDupeitgKiUggsF0TLmvX0zHnf6gxgWYYD2AsRBONVx5paxFJb6zkfpX+cHnlScYGRXfPI74CzXFT2eSuETQXA3dXuV/uYCpaKxYqT6qtBReTbI7Wow6lYr7Wkwd4F8Q22NbF9THMOZnG6srA7pnwNLZIXKwDokUORAV3HyonW6FBlC0Op389PTCgnvNQtRxjr6ziBphNwlk9NqFDlXU/VXRaNUWxChRtdGA6zVU+N3Xz+NClEmNCDmhLgO3rCYNgM0I2H2bNFwBY3JvfnWZYXh3KZId8/sjh8cZ5ORTtLA1QcYivRYlJQoqPD+1lqN/CH0rL2zlz8sIhfun17ZhAjjcknHMMubnGbSW715eRU2RLHnwXOHJBvnj6x2qLxTiK7gYEojYz1RtGqzin/eDlMfYnhJoXj7BLlCkfPTw/9A9YVVjYkH45OA/pBaBtfenWK5aRpzlMBYhqStTVsHwm6aqGRC2bgynVoK9fdn0tgdHoyAGnWM/t/OcSs/2lA7Hsbz6WMd5aMOGRA1QP4wnWJQqXXBlp2Tres/rNv6PzMNwgQplT1q+ahizv5NERSRNC6Ff7vnCJ+sW8aJum9qbA8B3EjhKA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
