travis:
  secure:
    BINSTAR_TOKEN: EG5m0nOsvuqVJM7RfSQlC9pUGl4VxCwgfXxTT94nhecq5vdjK4E5S9N3xgBBoy9u47hqir7RNJ64lWo0eRwrISMarJJteHEzKTTRuwdvJ0e597PaewOasUNrhaCfXff1sUPQWtwllqoV0+R5vr6gihZZ5Lt6YqcJr47EoYQJPs34s09lZ4ODcxv3uqog0Wox+A4y/T7A06yXyeq0Qk/jzXdo7JjRsk+5ZQl1JIYInjAtIaWgy12P8+Nt8GBvq/JUO9+cs6ZxdF27L9hHLunA8gmssF/ZiMqFM0h5SNn7z2q2NLHkhtF1Ac9PFfeE+FpsA3s9Y7q6aenljMIpUK0X1+mlyhuetxWDBgNZC9gKarOxhgqiXwktzqtnIBGlOMzNMMY27VfQWCqeJtttnsCWnLnF5c5IrLMlaUQFDal92e7cGiAwxPkdWTuQAGTUayyI5VfkyUtT0PuK5SbVU/dU3GnDqF4cWGGi3pzcCOG6JhFSHLsU6VxUQT6pSAJvaIF9qE59y7C8g3i5e8MR64eI3rYoaNlpliUQAa6TFM9cDXvkDLKnU8rBKjyl0/fy3BReXoIVvzRiAEVLwWhVI9n1Pq7ODQVZzthi2qmeKp56bzss3TcQ7NpyWxlZcjuxlMaOIU8XEfJ1Q+IZVcB8R+y7HkaWGLFkplJcIepRK5UqdHs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
